cc_test(
    name = "windowing-test",
    srcs = ["windowing-test.cc"],
    deps = [
        "@gtest//:main",
        "//lib:windowing",
    ],
    copts = ["-Iexternal/gtest/include", "-Iinclude"],
)