# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
    
on: 
  push

jobs:
  checks:
    name: run
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install OpenGL
      run: sudo apt-get install libglu1-mesa-dev freeglut3-dev mesa-common-dev -y
    - name: Install GLFW
      run: sudo apt-get install libglfw3-dev
    - name: Windowing test
      uses: ngalaiko/bazel-action/2.0.0@master
      with:
        args: run //examples:windowing-test 
